micronaut:
  application:
    name: carros
datasources:
  default:
    url: jdbc:mysql://localhost:3306/carrosGrpc
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true

logger:
  levels:
    io.micronaut.transaction: DEBUG